#!/bin/env make
# 
# created by Sebastian Ehlert in March 2018 (v 2.1)
#
###------------------------------------------------------------------------###
# specifiy where you are in the source tree
MAINDIR := ..

###------------------------------------------------------------------------###
# everything else is set here:
include $(MAINDIR)/makefile.default

